export const ROUTES = {
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/products/:id',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDERS: '/orders',
  ORDER_DETAIL: '/orders/:id',
  WISHLIST: '/wishlist',
  LOGIN: '/login',
  REGISTER: '/register',
  ACCOUNT: '/account',
  ADMIN: {
    ROOT: '/admin',
    PRODUCTS: '/admin/manage-products',
    ORDERS: '/admin/manage-orders',
    USERS: '/admin/manage-users',
    CATEGORIES: '/admin/manage-categories',
  },
} as const